### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by serisman** [free-pdk/easy-pdk-includes#1]
This repo need a clearly identified LICENSE so people know what can and cannot be done with it.

@freepdk, my preference for this is MIT, but these files have their roots from easy-pdk-programmer-software which is GPL v3.  Are you ok with (re-)licensing these include files as MIT, or should we keep this one as GPL v3?

**Comment by spth** [comment]
SDCC uses GPL2+LE (i.e, GPL 2 or later with liking exception) for its library.
Whatever is chosen should be compatible with that, at least for the part that is supposed to go into SDCC later.

**Comment by serisman** [comment]
> SDCC uses GPL2+LE (i.e, GPL 2 or later with liking exception) for its library.
> Whatever is chosen should be compatible with that, at least for the part that is supposed to go into SDCC later.

This repo is the programmer specific include files (i.e. calibration routines) and is not currently intended to be included with SDCC.  But, your comment would apply to the pdk-includes repo: https://github.com/free-pdk/pdk-includes/issues/5

**Comment by serisman** [comment]
Pull Request adding Copyright and LICENSE information: https://github.com/free-pdk/easy-pdk-includes/pull/2

**Comment by freepdk** [comment]
I'm not sure if the old LGPL is the right choice for headers which are included in a linked program.

I think GPL + LinkException is a better choice for this.

**Comment by serisman** [comment]
> I'm not sure if the old LGPL is the right choice for headers which are included in a linked program.
> 
> I think GPL + LinkException is a better choice for this.

Do you have a link that shows that as being a real thing?

I couldn't find it on http://www.gnu.org/licenses, and it isn't directly listed on their exceptions page either: https://www.gnu.org/licenses/exceptions.html

GitHub doesn't know about it: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

SPDX doesn't directly list it (unless it is one of the deprecated ones): https://spdx.org/licenses/

Wikipedia isn't really all that clear, although they do list LGPL as being related: https://en.wikipedia.org/wiki/GPL_linking_exception

Or, do we just list this as GPL 2.0 and include our own exception text (similar to what SDCC uses)?  That feels a bit dirty to not use an 'official' license, but maybe it is ok?

**Comment by freepdk** [comment]
https://en.wikipedia.org/wiki/GPL_linking_exception

In SDCC I only found this:
https://sourceforge.net/p/sdcc/code/HEAD/tree/trunk/sdcc/doc/README.txt
https://sourceforge.net/p/sdcc/code/HEAD/tree/trunk/sdcc/COPYING

=> we need to ask @spth 

Linking Excpetion:
You might put the repo under GPL LICENSE and then add a "LICENSE-ADDITIONAL" containing the linking exception.

**Comment by freepdk** [comment]
> Or, do we just list this as GPL 2.0 and include our own exception text (similar to what SDCC uses)? That feels a bit dirty to not use an 'official' license, but maybe it is ok?

But you use an official license. You just add an additional exception.

**Comment by serisman** [comment]
Ok, here is a different PR with GPL v2 with Linking Exception: https://github.com/free-pdk/easy-pdk-includes/pull/3

**Comment by serisman** [comment]
Copyright and LICENSE information was merged via pull request #3
